version: '3.9'

services:
  backend:
    container_name: cashforce_back
    build: ./backend
    working_dir: /app
    command: npm run dev
    restart: always
    depends_on:
      - db
    ports:
      - 3001:3001
    environment:
      - API_PORT=3001
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
    volumes:
      - ./backend/src:/app/src
  db:
    container_name: db
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: always